

import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


public class Location extends javax.swing.JFrame {

    /**
     * Creates new form Location
     */
    public Location() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtendtime = new javax.swing.JTextField();
        txtlocationid = new javax.swing.JTextField();
        txtlocation = new javax.swing.JTextField();
        txtstarttime = new javax.swing.JTextField();
        lbletime = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbllocid = new javax.swing.JLabel();
        lbllocation = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        lblstime = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dtp1 = new org.jdesktop.swingx.JXDatePicker();
        btnhome = new javax.swing.JButton();
        btnenter1 = new javax.swing.JButton();
        btnhome1 = new javax.swing.JButton();
        btnhome2 = new javax.swing.JButton();
        btnhome3 = new javax.swing.JButton();
        btnhome4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Camp Details");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Camp Details");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 630, 70));

        txtendtime.setText("Enter end time here");
        txtendtime.setName(""); // NOI18N
        txtendtime.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtendtimeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtendtimeFocusLost(evt);
            }
        });
        getContentPane().add(txtendtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 250, -1));

        txtlocationid.setText("Enter Location ID");
        txtlocationid.setName(""); // NOI18N
        txtlocationid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtlocationidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtlocationidFocusLost(evt);
            }
        });
        txtlocationid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlocationidActionPerformed(evt);
            }
        });
        getContentPane().add(txtlocationid, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 250, -1));

        txtlocation.setText("Enter Location here");
        txtlocation.setName(""); // NOI18N
        txtlocation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtlocationFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtlocationFocusLost(evt);
            }
        });
        getContentPane().add(txtlocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 250, -1));

        txtstarttime.setText("Enter start time here");
        txtstarttime.setName(""); // NOI18N
        txtstarttime.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtstarttimeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtstarttimeFocusLost(evt);
            }
        });
        txtstarttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstarttimeActionPerformed(evt);
            }
        });
        getContentPane().add(txtstarttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 250, -1));

        lbletime.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        lbletime.setForeground(new java.awt.Color(255, 255, 255));
        lbletime.setText("End Time");
        getContentPane().add(lbletime, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(": ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 30, 20));

        lbllocid.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        lbllocid.setForeground(new java.awt.Color(255, 255, 255));
        lbllocid.setText("Location ID");
        getContentPane().add(lbllocid, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, -1, -1));

        lbllocation.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        lbllocation.setForeground(new java.awt.Color(255, 255, 255));
        lbllocation.setText("Location");
        getContentPane().add(lbllocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, -1));

        lbldate.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        lbldate.setForeground(new java.awt.Color(255, 255, 255));
        lbldate.setText("Date");
        getContentPane().add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, -1, -1));

        lblstime.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        lblstime.setForeground(new java.awt.Color(255, 255, 255));
        lblstime.setText("Start Time");
        getContentPane().add(lblstime, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(": ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 30, 20));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(": ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 30, 20));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(": ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 30, 20));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(": ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 30, 20));

        dtp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtp1ActionPerformed(evt);
            }
        });
        getContentPane().add(dtp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 250, -1));

        btnhome.setBackground(new java.awt.Color(153, 153, 153));
        btnhome.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnhome.setText("Home");
        btnhome.setBorder(null);
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 530, 210, 40));

        btnenter1.setBackground(new java.awt.Color(153, 153, 153));
        btnenter1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnenter1.setText("Enter");
        btnenter1.setBorder(null);
        btnenter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenter1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnenter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 530, 210, 40));

        btnhome1.setBackground(new java.awt.Color(153, 153, 153));
        btnhome1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnhome1.setText("Home");
        btnhome1.setBorder(null);
        btnhome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhome1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnhome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 530, 210, 40));

        btnhome2.setBackground(new java.awt.Color(153, 153, 153));
        btnhome2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnhome2.setText("Home");
        btnhome2.setBorder(null);
        btnhome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhome2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnhome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 530, 210, 40));

        btnhome3.setBackground(new java.awt.Color(153, 153, 153));
        btnhome3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnhome3.setText("Home");
        btnhome3.setBorder(null);
        btnhome3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhome3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnhome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 530, 210, 40));

        btnhome4.setBackground(new java.awt.Color(153, 153, 153));
        btnhome4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnhome4.setText("Home");
        btnhome4.setBorder(null);
        btnhome4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhome4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnhome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 530, 210, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\EAD Coursework\\photoes\\location.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtendtimeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtendtimeFocusGained
        // TODO add your handling code here:
         if(txtendtime.getText().equals("Enter end time here"))
        {
            txtendtime.setText("");
           txtendtime.setForeground(Color.black);
        }
       
        
        
    }//GEN-LAST:event_txtendtimeFocusGained

    private void txtendtimeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtendtimeFocusLost
        // TODO add your handling code here:
        if(txtendtime.getText().equals(""))
        {
            txtendtime.setText("Enter end time here");
           txtendtime.setForeground(Color.gray);
        }
        

    }//GEN-LAST:event_txtendtimeFocusLost

    private void txtlocationidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlocationidFocusGained
        // TODO add your handling code here:
         if(txtlocationid.getText().equals("Enter Location ID"))
        {
            txtlocationid.setText("");
            txtlocationid.setForeground(Color.black);
        }
         
    }//GEN-LAST:event_txtlocationidFocusGained

    private void txtlocationidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlocationidFocusLost
        // TODO add your handling code here:
         if(txtlocationid.getText().equals(""))
        {
            txtlocationid.setText("Enter Location ID");
            txtlocationid.setForeground(Color.gray);
        }
       
    }//GEN-LAST:event_txtlocationidFocusLost

    private void txtlocationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlocationFocusGained
        // TODO add your handling code here:
         if(txtlocation.getText().equals("Enter Location here"))
        {
            txtlocation.setText("");
            txtlocation.setForeground(Color.black);
        }
        
        
    }//GEN-LAST:event_txtlocationFocusGained

    private void txtlocationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlocationFocusLost
        // TODO add your handling code here:
        if(txtlocation.getText().equals(""))
        {
            txtlocation.setText("Enter Location ID");
            txtlocation.setForeground(Color.gray);
        }
        
       
        
    }//GEN-LAST:event_txtlocationFocusLost

    private void txtstarttimeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtstarttimeFocusGained
        // TODO add your handling code here:
        if(txtstarttime.getText().equals("Enter start time here"))
        {
            txtstarttime.setText("");
            txtstarttime.setForeground(Color.black);
        }
       
        
    }//GEN-LAST:event_txtstarttimeFocusGained

    private void txtstarttimeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtstarttimeFocusLost
        // TODO add your handling code here:
        if(txtstarttime.getText().equals(""))
        {
            txtstarttime.setText("Enter start time here");
           txtstarttime.setForeground(Color.gray);
        }
         
    }//GEN-LAST:event_txtstarttimeFocusLost

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        // TODO add your handling code here:
        home fr1=new home();
        fr1.show();//display home here
        
        dispose();//close current frame after open home
        
        
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btnenter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenter1ActionPerformed
        // TODO add your handling code here:
        try
        {
            int locationid;
            String locationname,date,starttime,endtime;
            locationid=Integer.parseInt(txtlocationid.getText());
            locationname=txtlocation.getText();
            Date datedate=dtp1.getDate();
            DateFormat dformat=new SimpleDateFormat("yyy-MM-dd");
            date=dformat.format(datedate);
            starttime=txtstarttime.getText();
            endtime=txtendtime.getText();
            {
            if(locationname.equals(""))
            {
                 JOptionPane.showMessageDialog(null,"Please enter location Name !");
            }
            if(date.equals(""))
            {
                 JOptionPane.showMessageDialog(null,"Please enter Date !");
            }
            if(starttime.equals(""))
            {
                 JOptionPane.showMessageDialog(null,"Please enter Starttime !");
            }
            if(endtime.equals(""))
            {
                 JOptionPane.showMessageDialog(null,"Please enter End time !");
            }
            }
            String dbpath="jdbc:mysql://localhost/blood_donation_center";
            Connection con=DriverManager.getConnection(dbpath,"tashini","123");
            Statement st=con.createStatement();
            st.executeUpdate("insert into bloodcamp Values('"+locationid+"','"+ locationname+"','"+date+"','"+ starttime+"','"+endtime+"')");
            JOptionPane.showMessageDialog(this,"Location Details Entered Successfully !");
            clearfields();
            
            
            
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_btnenter1ActionPerformed
        private void clearfields()
        {
            txtlocationid.setText(null);
            txtlocation.setText(null);
            txtstarttime.setText(null);
            txtendtime.setText(null);
        }
    private void btnhome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome1ActionPerformed

    private void btnhome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome2ActionPerformed

    private void btnhome3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhome3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome3ActionPerformed

    private void btnhome4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhome4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome4ActionPerformed

    private void txtlocationidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlocationidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlocationidActionPerformed

    private void txtstarttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstarttimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstarttimeActionPerformed

    private void dtp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtp1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Location().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnenter1;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnhome1;
    private javax.swing.JButton btnhome2;
    private javax.swing.JButton btnhome3;
    private javax.swing.JButton btnhome4;
    private org.jdesktop.swingx.JXDatePicker dtp1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbletime;
    private javax.swing.JLabel lbllocation;
    private javax.swing.JLabel lbllocid;
    private javax.swing.JLabel lblstime;
    private javax.swing.JTextField txtendtime;
    private javax.swing.JTextField txtlocation;
    private javax.swing.JTextField txtlocationid;
    private javax.swing.JTextField txtstarttime;
    // End of variables declaration//GEN-END:variables
}
