
import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnllogin = new javax.swing.JPanel();
        lblregister = new javax.swing.JLabel();
        lbladminid = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblposition = new javax.swing.JLabel();
        lblphone = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        lblpassword = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtadminid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        cmbposition = new javax.swing.JComboBox<>();
        txtemail = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        btnregister = new javax.swing.JButton();
        btnrsignin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrator Registration");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnllogin.setBackground(new java.awt.Color(51, 51, 51));

        lblregister.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lblregister.setForeground(new java.awt.Color(255, 255, 255));
        lblregister.setText("Register");
        pnllogin.add(lblregister);

        getContentPane().add(pnllogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 630, 70));

        lbladminid.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        lbladminid.setForeground(new java.awt.Color(255, 255, 255));
        lbladminid.setText("Admin ID");
        getContentPane().add(lbladminid, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, -1, -1));

        lblname.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        lblname.setForeground(new java.awt.Color(255, 255, 255));
        lblname.setText("Name");
        getContentPane().add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));

        lblemail.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        lblemail.setForeground(new java.awt.Color(255, 255, 255));
        lblemail.setText("Email");
        getContentPane().add(lblemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, -1));

        lblposition.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        lblposition.setForeground(new java.awt.Color(255, 255, 255));
        lblposition.setText("Position");
        getContentPane().add(lblposition, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, -1, -1));

        lblphone.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        lblphone.setForeground(new java.awt.Color(255, 255, 255));
        lblphone.setText("Phone");
        getContentPane().add(lblphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, -1));

        lblusername.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        lblusername.setForeground(new java.awt.Color(255, 255, 255));
        lblusername.setText("Username");
        getContentPane().add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, -1, -1));

        lblpassword.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        lblpassword.setForeground(new java.awt.Color(255, 255, 255));
        lblpassword.setText("Password");
        getContentPane().add(lblpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, -1, -1));

        txtusername.setText("Enter Username here");
        txtusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtusernameFocusLost(evt);
            }
        });
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, 250, -1));

        txtadminid.setText("Enter Admin ID here");
        txtadminid.setName(""); // NOI18N
        txtadminid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtadminidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtadminidFocusLost(evt);
            }
        });
        getContentPane().add(txtadminid, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 250, -1));

        txtname.setText("Enter Name here");
        txtname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnameFocusLost(evt);
            }
        });
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 250, -1));

        cmbposition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Position--", "Doctor", "Nursing Officer", " ", " " }));
        getContentPane().add(cmbposition, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 250, -1));

        txtemail.setText("Enter Email here");
        txtemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtemailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtemailFocusLost(evt);
            }
        });
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 250, -1));

        txtphone.setText("Enter phone here");
        txtphone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtphoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtphoneFocusLost(evt);
            }
        });
        getContentPane().add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 250, -1));
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 250, -1));

        btnregister.setBackground(new java.awt.Color(153, 153, 153));
        btnregister.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnregister.setText("Register");
        btnregister.setBorder(null);
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, 210, 40));

        btnrsignin.setBackground(new java.awt.Color(153, 153, 153));
        btnrsignin.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnrsignin.setText("Sign In");
        btnrsignin.setBorder(null);
        btnrsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrsigninActionPerformed(evt);
            }
        });
        getContentPane().add(btnrsignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 600, 210, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(": ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, 30, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(": ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 30, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(": ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 30, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(": ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 30, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(": ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 30, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(": ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 30, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(": ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 30, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\EAD Coursework\\photoes\\jjjjj.png")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        setSize(new java.awt.Dimension(1014, 730));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtadminidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtadminidFocusGained
        // TODO add your handling code here:
        if(txtadminid.getText().equals("Enter Admin ID here"))
        {
            txtadminid.setText("");
            txtadminid.setForeground(Color.black);
        }
       
    }//GEN-LAST:event_txtadminidFocusGained

    private void txtadminidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtadminidFocusLost
        // TODO add your handling code here:
        if(txtadminid.getText().equals(""))
        {
            txtadminid.setText("Enter Admin ID here");
            txtadminid.setForeground(Color.gray);
        }
        
        
    }//GEN-LAST:event_txtadminidFocusLost

    private void txtnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusGained
        // TODO add your handling code here:
        if(txtname.getText().equals("Enter Name here"))
        {
            txtname.setText("");
            txtname.setForeground(Color.black);
        }
        
        
    }//GEN-LAST:event_txtnameFocusGained

    private void txtnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusLost
        // TODO add your handling code here:
         if(txtname.getText().equals(""))
        {
            txtname.setText("Enter Name here");
            txtname.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_txtnameFocusLost

    private void txtemailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemailFocusGained
        // TODO add your handling code here:
        if(txtemail.getText().equals("Enter Email here"))
        {
            txtemail.setText("");
            txtemail.setForeground(Color.black);
        }
        
         
    }//GEN-LAST:event_txtemailFocusGained

    private void txtemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemailFocusLost
        // TODO add your handling code here:
        if(txtemail.getText().equals(""))
        {
            txtemail.setText("Enter Email here");
            txtemail.setForeground(Color.gray);
        }
        
        
    }//GEN-LAST:event_txtemailFocusLost

    private void txtphoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtphoneFocusGained
        // TODO add your handling code here:
        if(txtphone.getText().equals("Enter phone here"))
        {
            txtphone.setText("");
            txtphone.setForeground(Color.black);
        }
         
    }//GEN-LAST:event_txtphoneFocusGained

    private void txtphoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtphoneFocusLost
        // TODO add your handling code here:
        if(txtphone.getText().equals(""))
        {
            txtphone.setText("Enter phone here");
            txtphone.setForeground(Color.gray);
        }
       
    }//GEN-LAST:event_txtphoneFocusLost

    private void txtusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusGained
        // TODO add your handling code here:
        if(txtusername.getText().equals("Enter Username here"))
        {
            txtusername.setText("");
            txtusername.setForeground(Color.black);
        }
        
    }//GEN-LAST:event_txtusernameFocusGained

    private void txtusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusLost
        // TODO add your handling code here:
        if(txtusername.getText().equals(""))
        {
            txtusername.setText("Enter Username here");
            txtusername.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_txtusernameFocusLost

    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed
        // TODO add your handling code here:
        
            
        try
        {
            String adminid,name,email,position,tp,username,password;
            adminid=txtadminid.getText();
            name=txtname.getText();
            email=txtemail.getText();
            position=cmbposition.getSelectedItem().toString();
            tp=txtphone.getText();
            username=txtusername.getText();
            password=txtpassword.getText();
            {
            if( adminid.equals(""))
            {
                 JOptionPane.showMessageDialog(null,"Please enter Admin ID!");
            }
             if( name.equals(""))
            {
                 JOptionPane.showMessageDialog(null,"Please enter Name !");
            }
             if( email.equals(""))
            {
                 JOptionPane.showMessageDialog(null,"Please enter Email !");
            }
              if( tp.equals(""))
            {
                 JOptionPane.showMessageDialog(null,"Please enter Contact Number !");
            }
             if(  username.equals(""))
            {
                 JOptionPane.showMessageDialog(null,"Please enter Username !");
            }
            if( password.equals(""))
            {
                 JOptionPane.showMessageDialog(null,"Please enter password !");
            }
            }
            
            String dbpath="jdbc:mysql://localhost/blood_donation_center";
            Connection con=DriverManager.getConnection(dbpath,"tashini","123");
            Statement st=con.createStatement();
            st.executeUpdate("insert into administrator Values('"+adminid+"','"+name+"','"+email+"','"+position+"','"+tp+"','"+username+"','"+password+"')");
            JOptionPane.showMessageDialog(this,"Registration Successful !");
            
            
            
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_btnregisterActionPerformed

    private void btnrsigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrsigninActionPerformed
        // TODO add your handling code here:
        //open login form
        login fr1=new login();
        fr1.show();//display login here
        
        dispose();//close current frame after open login
        
        
        
    }//GEN-LAST:event_btnrsigninActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregister;
    private javax.swing.JButton btnrsignin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbposition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbladminid;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblphone;
    private javax.swing.JLabel lblposition;
    private javax.swing.JLabel lblregister;
    private javax.swing.JLabel lblusername;
    private javax.swing.JPanel pnllogin;
    private javax.swing.JTextField txtadminid;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
